version: "3.7"

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '3379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    restart: unless-stopped
    env_file: .env
    links: [cache]
    depends_on:
      - cache
    volumes:
      - '.:/app'

volumes:
  cache:
    driver: local
